### ISSUE TITLE
How to solve the problem of import.meta.env undefined problem?

### ISSUE THREAD

**Issue by BigCoal** [starkovsky/vue3-vite-ts#234]

**Comment by BigCoal** [comment]
![image](https://user-images.githubusercontent.com/32946565/148179923-b04f0d7a-767f-4f36-8a68-1f48e82a736a.png)

**Comment by BigCoal** [comment]
![image](https://user-images.githubusercontent.com/32946565/148180604-dff2bcb5-823d-4483-9afa-da403d8aa01a.png)

**Comment by starkovsky** [comment]
Hello, you need mock full runtimeEnv import

just see
https://github.com/starkovsky/vue3-vite-ts/blob/08019d928f1b91bf5898e3036a7d04855edf416e/tests/Home.spec.ts#L16-L24
